"""Add expected_users column to projects

Revision ID: 7566a6e5e02f
Revises: 7b46d48c39b3
Create Date: 2026-08-22 01:59:31.293117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7566a6e5e02f'
down_revision = '7b46d48c39b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_users', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('expected_users')

    # ### end Alembic commands ###
